#Trisha Andres                                                                
#CPSC 1071: Section 2                                                         
#Group 6: C--                                                                  
#02/12/2023

#compile code to executable file
compile:
	g++ calculate.cpp -o calculate.out

#run executable
run:
	./calculate.out

#clean executable
clean:
	rm *.out
