#Trisha Andres
#CPSC 1070: Section 2
#Group B6: C--
#03/01/2023

compile:
	g++ Driver.cpp Date.o ParkingWars.o MysteryMachine.o -o battle.out

date: 
	g++ -c Date.h Date.cpp  

parking:
	g++ -c ParkingWars.h ParkingWars.cpp

run:
	./battle.out

clean:
	rm *.out
