#Trisha Andres
#CPSC 1070: Section 2
#B6: C--
#04/9/23                                                              
     

compile:
	g++ -Wall Queue.h Queue.cpp Cipher.h Cipher.cpp Project3.cpp -o project3.out
q:
	g++ Queue.h Queue.cpp -c -Wall

cipher:
	g++ Cipher.h Cipher.cpp -c -Wall

comp:
	g++ Queue.o Cipher.o Project3.cpp -Wall -o project3.out

run:
	./project3.out

clean:
	rm *.out

no:
	rm *.o
